### ISSUE TITLE
Consider namespacing collections

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-zcap-storage#1]
https://github.com/digitalbazaar/bedrock-zcap-storage/blob/master/lib/storage.js#L39

The use of a generic term like `authorization` as a collection name has led me to consider why we're not already namespacing all the collection names.

The typical convention has been that `bedrock-keys` could create a collection called `keys`.

This module has gone rogue and created a collection called `authorization` in addition to `zcap`.

I propose that `authorization` and any additional collections used by this module be `zap-authorization` or `zcap-foo`.

**Comment by dlongley** [comment]
`zcap-authorization`, `zcap-delegation`, and.... `zcap`? `zcap-storage`? ... what's the last collection that is intended to be used to allow invokers to keep track of their zcaps? It may be that we say to just use EDVs for that in the future, but we need a name for NOW.

**Comment by mattcollier** [comment]
Thank you, I'm going with:
- zcap-authorization
- zcap-revocation
- zcap-storage
