### ISSUE TITLE
FIXME Count 2

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-zcap-storage#4]
- [ ] FIXME remove options.fields from all libraries that call on zcap-storage
       Commit: (eda7c54) Update mongo methods to 3.5 api.
       File:  [lib/storage.js:200](https://github.com/digitalbazaar/bedrock-zcap-storage/blob/master/lib/storage.js#L200)
       andrewjones commented a month ago

  - [ ] FIXME remove options.fields from all libraries that call on zcap-storage
       Commit: (eda7c54) Update mongo methods to 3.5 api.
       File:  [lib/storage.js:323](https://github.com/digitalbazaar/bedrock-zcap-storage/blob/master/lib/storage.js#L323)
       andrewjones commented a month ago

**Comment by dlongley** [comment]
These have been addressed.
